// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7RXu-boUSUjedRFpkZlHAcfoKJDc888',
    appId: '1:91338827024:web:147304bbaa1883b1b5f195',
    messagingSenderId: '91338827024',
    projectId: 'smart-card-scanner-1231a',
    authDomain: 'smart-card-scanner-1231a.firebaseapp.com',
    storageBucket: 'smart-card-scanner-1231a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YFT1vs4hcRJ4O5_P7hfugwO5uLl2zrY',
    appId: '1:91338827024:android:00f6d4725c98cbadb5f195',
    messagingSenderId: '91338827024',
    projectId: 'smart-card-scanner-1231a',
    storageBucket: 'smart-card-scanner-1231a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJBtJwX1jzhOXu_B0agG-46Kh8uY2PM8',
    appId: '1:91338827024:ios:a77f2efe0d0d58e8b5f195',
    messagingSenderId: '91338827024',
    projectId: 'smart-card-scanner-1231a',
    storageBucket: 'smart-card-scanner-1231a.firebasestorage.app',
    iosBundleId: 'com.example.smartCardScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJBtJwX1jzhOXu_B0agG-46Kh8uY2PM8',
    appId: '1:91338827024:ios:a77f2efe0d0d58e8b5f195',
    messagingSenderId: '91338827024',
    projectId: 'smart-card-scanner-1231a',
    storageBucket: 'smart-card-scanner-1231a.firebasestorage.app',
    iosBundleId: 'com.example.smartCardScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_7RXu-boUSUjedRFpkZlHAcfoKJDc888',
    appId: '1:91338827024:web:f4d49ed3770d1facb5f195',
    messagingSenderId: '91338827024',
    projectId: 'smart-card-scanner-1231a',
    authDomain: 'smart-card-scanner-1231a.firebaseapp.com',
    storageBucket: 'smart-card-scanner-1231a.firebasestorage.app',
  );
}
